### ISSUE TITLE
Remove the calls to add Tracks to the Nengo Builder function dictionary

### ISSUE THREAD

**Issue by mundya** [ctn-waterloo/nengo_pushbot#2]
As `Tracks` is a subclass of `Nengo.Node` it will now be built like a normal Node.  Hence, remove lines:

``` python
from nengo.builder import _builder_func_dict as bfd
bfd[Tracks] = bfd[nengo.Node]
```

**Comment by tcstewar** [comment]
Yup -- that's there because the nengo reference builder doesn't handle subclasses of Node -- it looks for an exact match for the class.  There's definitely a chance that this'll change, though.

**Comment by mundya** [comment]
It's changed in the public repository I believe.
